# Generated by Django 5.1.3 on 2024-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa_deportiva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='talla',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], max_length=10),
        ),
    ]
